[package]

	name    = "ou"
	version = "0.1.0-2017.11.14-alpha"
	authors = [ "Naja Melan <najamelan@autistici.org>" ]

[dependencies]

	pwhash    = "*"
	pgs-files = "*"
	privdrop  = "*"
	users     = "*"

